public enum TipoToken{
    PROGRAM, BEGIN, END, READ, WRITE, IF, THEN, ELSE, WHILE, DO, INT,
    ID, NUMBER, ASSIGN, PLUS, MINUS, TIMES, DIVIDE, EQ, LT, GT, LPAREN, RPAREN,
    LBRACE, RBRACE, SEMICOLON, COLON, COMMA, DOT, WHITESPACE, COMMENT, LE, GE,
    NUMBERREAL, VAR, FLOAT
}